version: "3.7"

services:

  ingress:
    image: maxwellflitton/compute-unit
    environment:
      - 'TO_DO_DB_URL=${DATABASE_URL}'
      - 'AUTH_DB_URL=${DATABASE_URL}'
      - 'JWT_SECRET=secret'
      - 'CACHE_API_URL=redis://cache:6379'
      - 'ELASTICSEARCH_URL=http://elasticsearch:9200/logs/_doc'
    ports:
      - "8001:8001"
  nginx:
    container_name: 'nginx'
    image: "nginx:latest"
    ports:
      - "80:80"
    links:
      - ingress
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  cache:
    container_name: 'to-do-redis'
    image: 'maxwellflitton/redis-cache'
    restart: always
    ports:
      - '6379:6379'
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
