[package]
name = "auth-axum-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
axum = { version = "0.8.4" }
auth-core = { path = "../../core" }
auth-dal = { path = "../../dal" }
glue = { path = "../../../../glue", features = ["axum"] }
base64 = "0.22.1"
