[package]
name = "to-do-atomic-http-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
glue = { path = "../../../../glue" }
to-do-kernel = { path = "../../kernel", features = ["http"] }
tokio = { version = "1.39.2", features = ["full"] }
cache-client = { path = "../../../user-session-cache/cache-client" }
dal = { path = "../../dal", features = ["sqlx-postgres"]}
sqlx = { version = "0.8.1", features = ["postgres", "json", "runtime-tokio"] }
