version: "3.7"

services:

  postgres:
    container_name: 'to-do-postgres'
    image: 'postgres:16.3'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=to_do'
      - 'POSTGRES_PASSWORD=password'
  cache:
    container_name: 'to-do-redis'
    build: './nanoservices/user-session-cache/cache-module'
    restart: always
    ports:
      - '6379:6379'
  
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
#     container_name: elasticsearch
#     environment:
#       - discovery.type=single-node
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     volumes:
#       - es_data:/usr/share/elasticsearch/data
#     ports:
#       - "9200:9200"
#       - "9300:9300"

#   kibana:
#     image: docker.elastic.co/kibana/kibana:7.13.4
#     container_name: kibana
#     ports:
#       - "5601:5601"
#     environment:
#       ELASTICSEARCH_URL: http://elasticsearch:9200
#     depends_on:
#       - elasticsearch

#   otel-collector:
#     image: otel/opentelemetry-collector:latest
#     container_name: otel-collector
#     ports:
#       - "55680:55680"
#       - "55681:55681"
#       - "4317:4317"
#       - "4318:4318"
#     volumes:
#       - ./otel-config.yml:/etc/otel/config.yml
#     command: ["--config=/etc/otel/config.yml"]

# volumes:
#   es_data:
#     driver: local
