receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  elastic:
    apm_server_url: "http://elasticsearch:8200"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [elastic]
    metrics:
      receivers: [otlp]
      exporters: [elastic]
