[workspace]
resolver = "2"

members = [
    "to_do/core",
    "to_do/dal",
    "to_do/networking/actix_server",
    "to_do/networking/axum_server", 
    "to_do/networking/hyper_server",
    "to_do/networking/rocket_server"
]
