[package]
name = "implementing-a-http-server-in-hyper"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "1.6.0", features = ["full"] }
tokio = { version = "1.45.0", features = ["full"] }
http-body-util = "0.1.3"
hyper-util = { version = "0.1.11", features = ["full"] }
