[package]
name = "wasm-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
kernel = { path = "../kernel" }
serde = { version = "1.0.201", features = ["derive"] }

[lib]
crate-type = ["cdylib"]
