
[workspace]
resolver = "2"
members = [ 
    "glue",
    "ingress",
    "ingress/frontend/rust-interface",
    "nanoservices/to_do/core",
    "nanoservices/to_do/dal",
    "nanoservices/to_do/networking/actix_server"
]
