version: "3.7"

services:

  postgres:
    container_name: 'to-do-postgres'
    image: 'postgres:16.3'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=to_do'
      - 'POSTGRES_PASSWORD=password'
  cache:
    container_name: 'to-do-redis'
    build: './nanoservices/user-session-cache/cache-module'
    restart: always
    ports:
      - '6379:6379'
